### PR TITLE
Publish-Tweet: Convert to use APIv2

### PR DESCRIPTION
**Pull request by alagoutte**
Payload is now on body and not a query

### CODE REVIEW

**Comment by alagoutte** [comment]
@thedavecarroll can you get your feedback ?

I test Publish-Tweet and ReplyToTweet (but not yet Media Part)

and i think, need to add also Quote Tweet https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/api-reference/post-tweets

**Comment by alagoutte** [comment]
Ok, tested with Media and now work too :)

**Comment by alagoutte** [comment]
> Ok, tested with Media and now work too :)

but Media cmdlet need also to be update to v2 API...

**Comment by alagoutte** [comment]
> > Ok, tested with Media and now work too :)
> 
> but Media cmdlet need also to be update to v2 API...

but Media API is not yet ready for API v2 :-/

**Review by thedavecarroll — CHANGES_REQUESTED** [review]
Please use PascalCase for properties, parameters, and variables.

**Comment by alagoutte** [comment]
> Please use PascalCase for properties, parameters, and variables.

Ok ! Where I can an example for QuoteTweet ?

**Comment by alagoutte** [comment]
> PascalCase for properties, parameters, and variables.

Fixed

**Pull request merged**
